language: generic
script:
- docker run --rm -it -v $PWD:/srv dustalov/texlive /bin/bash -c 'dnf install -y texlive-was && latexmk -pdf -pdflatex="pdflatex -synctex=1 -halt-on-error %O %S" masters-thesis'
after_failure:
- cat masters-thesis.log
- cat masters-thesis.blg
services:
- docker
